### ISSUE TITLE
Question: How does validInput functino work in pdf.js?

### ISSUE THREAD

**Issue by adam-beck** [vnglst/latex-letter#1]
I posted the following on the Reddit thread but thought maybe it was better suited for the repo instead.

> How does the [validInput](https://github.com/vnglst/latex-letter/blob/master/routes/pdf.js#L26-L37) function of `pdf.js` work? To me, it would seem that if there *isn't* a `body.subject` then it would still pass as valid and skip the other checks because of the return statement? Yet, when I try not sending a `subject` I still get the error message "Incorrect data. Some form fields were empty.".
>
> Could somebody explain how this manages to work? My brain must've shut down for the weekend.

**Comment by vnglst** [comment]
Hi! Say your question on Reddit and now here. (I'll just copy paste my answer here. That was quick hack to make sure the LaTeX compiler gets a value for some fields. Not all fields are required so I added a "return true" for the subject field to let that pass.

So your interpretation of my (terribly dirty) code was correct. The thing is, that's not on the server right now. I'm having trouble building the latest Docker images, so I haven't deployed the new code just yet. I hope to do that tonight! I'll let you know and thanks!

**Comment by vnglst** [comment]
I just managed to deploy a new version, with a new validation function. It should at least work now.

**Comment by adam-beck** [comment]
Thanks for replying to my question! And very unique project! I would never have thought to work with LaTeX.

**Comment by vnglst** [comment]
Thanks, very glad you like it.
